### ISSUE TITLE
Password not displayed when emailing setup

### ISSUE THREAD

**Issue by LanceHaverkamp** [autocrypt-thunderbird/autocrypt-thunderbird#8]
The password (numeric9x4) is **not** displayed when emailing a setup message; though it is displayed when creating a local backup.

This prevents an **emailed** setup from ever being installed on another device.  The work-around is transferring a physical file, such as on a flash drive, since a password is only shown when backing-up. 

OS: KDE-Neon (Ubuntu 18.04 based)
Thunderbird Version: 68.1.1 (64-bit from Mozilla--not Ubuntu)
Autocrypt plugin Version: 0.9.1.6

I just double-checked, the same thing happens on my wife's Windows 10 installation.

**Comment by Valodim** [comment]
Hi, thanks for reporting! :)

This is fixed in a release that I uploaded weeks ago, but isn't yet through review. I also improved those dialogs in my working branch, they should be much nicer soon.

I'll leave this issue open, and close it once that release is actually deployed. Unfortunately, there's not much I can do to help that process along.
